version: '3.8'

services:
  tweetmicroservice:
    build:
      context: ./TweetMicroService/TweetMicroService # Ensure this is the correct context where your Dockerfile is located
      dockerfile: Dockerfile # Ensure this is the correct Dockerfile path
      args:
        - GITHUB_SHA=${GITHUB_SHA}
        - GITHUB_REF=${GITHUB_REF}
    ports:
      - "7120:80"
    networks:
      - mynetwork
    image: "${GAR_ZONE}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${IMAGE}:latest"

networks:
  mynetwork:
    driver: bridge
