version: '3.8'

services:
  tweetmicroservice:
    build:
      context: ./TweetMicroService/TweetMicroService # Ensure this is the correct context where your Dockerfile is located
      dockerfile: Dockerfile # Ensure this is the correct Dockerfile path
    ports:
      - "7120:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
