apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetmicro-service-development
  labels:
    app: kweetmicro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetmicro-service
  template:
    metadata:
      labels:
        app: kweetmicro-service
    spec:
      containers:
        - name: kweetmicro-service
          image: europe-west4-docker.pkg.dev/centered-song-423220-i0/kwetter-repo/kwetter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kweetmicro-service-loadbalancer
spec:
  selector:
    app: kweetmicro-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer