apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetmicro-service-development
  labels:
    app: tweetmicro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetmicro-service
  template:
    metadata:
      labels:
        app: tweetmicro-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: tweetmicro-service
          image: europe-west4-docker.pkg.dev/centered-song-423220-i0/kwetter-repo/kwetter:kwetterlatest
          imagePullPolicy: Always
          ports:
            - containerPort: 80