apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: merva1998/fe:latest  # Ensure this matches the Docker Hub repository and tag
        ports:
        - containerPort: 3000
