apiVersion: v1
kind: Service
metadata:
    name: api-service
    labels:
        app: kwetter-api
spec:
    ports:
        - port: 80
          targetPort: 80
    selector:
        app: kwetter-api
    type: LoadBalancer