name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: kwetter-cluster-1    # cluster name
  GKE_ZONE: europe-west1   # cluster zone
  IMAGE: kwetter # image name
  IMAGE_TAG: kwetterlatest # image tag
  GAR_ZONE: europe-west4 # artifact registry zone
  GAR_REPO: kwetter-repo # artifact registry repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker-compose build
        docker-compose push

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GKE_PROJECT }}
      run: |
        gcloud container clusters get-credentials kwetter-cluster-1 --region europe-west1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deploy.yaml
        kubectl apply -f deploy.yaml