apiVersion: apps/v1
kind: Deployment
metadata:
    name: tweetmicro-service-development
    labels:
        app: tweetmicro-service
spec:
    replicas: 3
    selector:
        matchLabels:
            app: tweetmicro-service
    template:
        metadata:
            labels:
                app: tweetmicro-service
        spec:
            containers:
                - name: tweetmicro-service
                  image: kwetter-repo/kwetter
                  imagePullPolicy: Always
                  ports:
                   - containerPort: 80
